<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'product_id' => 18,
                'seller_id' => 6,
                'category_id' => 1,
                'title' => 'Sample Product 18',
                'slug' => 'sample-product-18',
                'description' => 'Sample',
                'price' => 30000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 19,
                'seller_id' => 6,
                'category_id' => 1,
                'title' => 'Sample Product 19',
                'slug' => 'sample-product-19',
                'description' => 'Sample',
                'price' => 1000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 20,
                'seller_id' => 6,
                'category_id' => 1,
                'title' => 'Sample Product 20',
                'slug' => 'sample-product-20',
                'description' => 'Sample',
                'price' => 20000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 23,
                'seller_id' => 6,
                'category_id' => 1,
                'title' => 'Sample Product 23',
                'slug' => 'sample-product-23',
                'description' => 'Sample',
                'price' => 25000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 25,
                'seller_id' => 6,
                'category_id' => 1,
                'title' => 'Sample Product 25',
                'slug' => 'sample-product-25',
                'description' => 'Sample',
                'price' => 1000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 51,
                'seller_id' => 22,
                'category_id' => 1,
                'title' => 'Sample Product 51',
                'slug' => 'sample-product-51',
                'description' => 'Sample',
                'price' => 250000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 55,
                'seller_id' => 7,
                'category_id' => 1,
                'title' => 'Sample Product 55',
                'slug' => 'sample-product-55',
                'description' => 'Sample',
                'price' => 3030000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 56,
                'seller_id' => 7,
                'category_id' => 1,
                'title' => 'Sample Product 56',
                'slug' => 'sample-product-56',
                'description' => 'Sample',
                'price' => 1500000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 60,
                'seller_id' => 7,
                'category_id' => 1,
                'title' => 'Sample Product 60',
                'slug' => 'sample-product-60',
                'description' => 'Sample',
                'price' => 3300000.00,
                'weight' => 100,
                'stock' => 10,
                'condition' => 'new',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
